[package]
name = "hello-rust-yew"
version = "0.1.0"
authors = ["nishiurahiroki <nishiurahiroki@gmail.com>"]

[dependencies]
stdweb = "0.4.2"
yew = { git = "https://github.com/DenisKolodin/yew.git", rev = "49319b8c02a8eeb15ed4c8a8761f83adcee856b0" }
serde = "1"
serde_json = "1"
serde_derive = "1"
